**TASK 1**




In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

np.random.seed(42)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X.flatten() + np.random.randn(100)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Feature values (X):")
print(X[:10])            #show first 10 samples

print("\nTarget values (y):")
print(y[:10])           #show fis 10 target values

print("\nX_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

Feature values (X):
[[0.74908024]
 [1.90142861]
 [1.46398788]
 [1.19731697]
 [0.31203728]
 [0.31198904]
 [0.11616722]
 [1.73235229]
 [1.20223002]
 [1.41614516]]

Target values (y):
[6.33428778 9.40527849 8.48372443 5.60438199 4.71643995 5.29307969
 5.82639572 8.67878666 6.79819647 7.74667842]

X_train shape: (80, 1)
X_test shape: (20, 1)
y_train shape: (80,)
y_test shape: (20,)


In [ ]:
from sklearn.linear_model import LinearRegression

# Create a Linear Regression model
model = LinearRegression()

# Train the model using the training data
model.fit(X_train, y_train)

print("Model training complete.")

Model training complete.


In [ ]:
# Generate predictions on the test set
y_pred = model.predict(X_test)

print("Predictions generated.")

# Show some actual vs. predicted values
print("\nActual vs. Predicted values (first 5 samples):")
for i in range(5):
    print(f"Actual: {y_test[i]:.2f}, Predicted: {y_pred[i]:.2f}")

Predictions generated.

Actual vs. Predicted values (first 5 samples):
Actual: 5.04, Predicted: 4.50
Actual: 8.87, Predicted: 9.15
Actual: 7.40, Predicted: 8.47
Actual: 7.07, Predicted: 7.85
Actual: 6.34, Predicted: 5.59


In [ ]:
import numpy as np

def mean_absolute_error(y_true, y_pred):
  return np.mean(np.abs(y_true - y_pred))

def mean_squared_error(y_true, y_pred):
  return np.mean((y_true - y_pred)**2)

def root_mean_squared_error(y_true, y_pred):
  return np.sqrt(mean_squared_error(y_true, y_pred))

def r_squared(y_true, y_pred):
  ss_total = np.sum((y_true - np.mean(y_true))**2)
  ss_residual = np.sum((y_true - y_pred)**2)
  return 1 - (ss_residual / ss_total)

print("NumPy metric functions defined.")

NumPy metric functions defined.


In [ ]:
# Calculate and print the metric values
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r_squared(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

Mean Absolute Error (MAE): 0.59
Mean Squared Error (MSE): 0.65
Root Mean Squared Error (RMSE): 0.81
R-squared (R2): 0.81


In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Calculate metrics using Scikit-learn
mae_sklearn = mean_absolute_error(y_test, y_pred)
mse_sklearn = mean_squared_error(y_test, y_pred)
rmse_sklearn = np.sqrt(mse_sklearn) # RMSE is the square root of MSE
r2_sklearn = r2_score(y_test, y_pred)

print("Metrics calculated using Scikit-learn:")
print(f"Mean Absolute Error (MAE): {mae_sklearn:.2f}")
print(f"Mean Squared Error (MSE): {mse_sklearn:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_sklearn:.2f}")
print(f"R-squared (R2): {r2_sklearn:.2f}")

Metrics calculated using Scikit-learn:
Mean Absolute Error (MAE): 0.59
Mean Squared Error (MSE): 0.65
Root Mean Squared Error (RMSE): 0.81
R-squared (R2): 0.81


As shown in the output above, the metrics calculated using the custom NumPy functions and Scikit-learn's built-in functions are the same, confirming the correctness of the NumPy implementations.

**Task 2**

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = (iris.target == 2).astype(int) # Virginica = 1, else 0

In [ ]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (120, 4)
X_test shape: (30, 4)
y_train shape: (120,)
y_test shape: (30,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Instantiate a KNeighborsClassifier object with n_neighbors=3
knn_model = KNeighborsClassifier(n_neighbors=3)

# Train the KNN model using the training data
knn_model.fit(X_train, y_train)

print("KNN model training complete with k=3.")

KNN model training complete with k=3.


In [ ]:
# Generate predictions on the test set
y_pred = knn_model.predict(X_test)

print("Predictions generated.")

# Print the first few predictions
print("\nFirst 5 predictions:")
print(y_pred[:5])

Predictions generated.

First 5 predictions:
[0 0 1 0 0]


In [ ]:
def calculate_confusion_matrix(y_true, y_pred):
  true_positives = 0
  false_positives = 0
  true_negatives = 0
  false_negatives = 0

  for true_label, predicted_label in zip(y_true, y_pred):
    if true_label == 1 and predicted_label == 1:
      true_positives += 1
    elif true_label == 0 and predicted_label == 1:
      false_positives += 1
    elif true_label == 0 and predicted_label == 0:
      true_negatives += 1
    elif true_label == 1 and predicted_label == 0:
      false_negatives += 1

  return true_positives, false_positives, true_negatives, false_negatives

print("Confusion matrix calculation function defined.")

Confusion matrix calculation function defined.


In [ ]:
# Calculate the confusion matrix components
true_positives, false_positives, true_negatives, false_negatives = calculate_confusion_matrix(y_test, y_pred)

# Print the calculated values
print(f"True Positives (TP): {true_positives}")
print(f"False Positives (FP): {false_positives}")
print(f"True Negatives (TN): {true_negatives}")
print(f"False Negatives (FN): {false_negatives}")

True Positives (TP): 11
False Positives (FP): 0
True Negatives (TN): 19
False Negatives (FN): 0


In [ ]:
from sklearn.metrics import confusion_matrix
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Calculate the confusion matrix using Scikit-learn
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix (Scikit-learn):")
print(cm)


Confusion Matrix (Scikit-learn):
[[19  0]
 [ 0 11]]


In [ ]:
def calculate_accuracy(true_positives, false_positives, true_negatives, false_negatives):
  """Calculates accuracy from confusion matrix components."""
  total_samples = true_positives + false_positives + true_negatives + false_negatives
  return (true_positives + true_negatives) / total_samples if total_samples > 0 else 0

def calculate_precision(true_positives, false_positives):
  """Calculates precision from confusion matrix components."""
  return true_positives / (true_positives + false_positives) if (true_positives + false_positives) > 0 else 0

def calculate_recall(true_positives, false_negatives):
  """Calculates recall from confusion matrix components."""
  return true_positives / (true_positives + false_negatives) if (true_positives + false_negatives) > 0 else 0

def calculate_f1_score(precision, recall):
  """Calculates F1-score from precision and recall."""
  return 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

print("Metric calculation functions defined.")

Metric calculation functions defined.


In [ ]:
# Calculate the metrics using the confusion matrix components
accuracy = calculate_accuracy(true_positives, false_positives, true_negatives, false_negatives)
precision = calculate_precision(true_positives, false_positives)
recall = calculate_recall(true_positives, false_negatives)
f1 = calculate_f1_score(precision, recall)

# Print the calculated metrics
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-score: {f1:.2f}")

Accuracy: 1.00
Precision: 1.00
Recall: 1.00
F1-score: 1.00


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Calculate metrics using Scikit-learn
accuracy_sklearn = accuracy_score(y_test, y_pred)
precision_sklearn = precision_score(y_test, y_pred)
recall_sklearn = recall_score(y_test, y_pred)
f1_sklearn = f1_score(y_test, y_pred)

print("Metrics calculated using Scikit-learn:")
print(f"Accuracy: {accuracy_sklearn:.2f}")
print(f"Precision: {precision_sklearn:.2f}")
print(f"Recall: {recall_sklearn:.2f}")
print(f"F1-score: {f1_sklearn:.2f}")

Metrics calculated using Scikit-learn:
Accuracy: 1.00
Precision: 1.00
Recall: 1.00
F1-score: 1.00


As shown in the output above, the metrics calculated using the custom functions and Scikit-learn's built-in functions are the same. This confirms that the implementations for Accuracy, Precision, Recall, and F1-score are correct. The model achieved perfect scores (1.00) for all these metrics on the test set, indicating excellent performance in classifying Virginica irises.